name: HomePharmacy
options:
  bundleIdPrefix: com.laboratory.work
  xcodeVersion: "15.0"
targets:
  HomePharmacy:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: HomePharmacy
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.laboratory.work.HomePharmacy
      DEVELOPMENT_TEAM: ""
